import member1 from "../assets/avatar1.webp";
import member2 from "../assets/avatar2.webp";
import member3 from "../assets/avatar3.webp";
import member4 from "../assets/avatar4.webp";
import member5 from "../assets/avatar5.webp";
import member6 from "../assets/avatar6.webp";

export const TEAM_MEMBERS = [
  {
    name: "Aarav Mehta",
    role: "Creative Director",
    bio: "Leads the visual direction and branding strategy with 10+ years of experience in design and storytelling.",
    src: member1,
    alt: "Aarav Mehta - Creative Director",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Riya Sharma",
    role: "Lead Developer",
    bio: "Expert in full-stack development, Riya turns bold ideas into scalable, high-performance products.",
    src: member2,
    alt: "Riya Sharma - Lead Developer",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Karan Patel",
    role: "Project Manager",
    bio: "Keeps everything on track with agile processes, ensuring smooth collaboration and on-time delivery.",
    src: member3,
    alt: "Karan Patel - Project Manager",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Anika Rao",
    role: "UX/UI Designer",
    bio: "Crafts intuitive user experiences that align design with business goals and user behavior.",
    src: member4,
    alt: "Anika Rao - UX/UI Designer",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Nikhil Verma",
    role: "Marketing Strategist",
    bio: "Connects data with creativity to drive traffic, leads, and conversions across digital channels.",
    src: member5,
    alt: "Nikhil Verma - Marketing Strategist",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Sneha Joshi",
    role: "Content Specialist",
    bio: "Creates compelling content that captures attention and communicates brand voice across all platforms.",
    src: member6,
    alt: "Sneha Joshi - Content Specialist",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Arjun Singh",
    role: "Backend Developer",
    bio: "Specializes in server-side architecture and database optimization to ensure robust and scalable applications.",
    src: member1,
    alt: "Arjun Singh - Backend Developer",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Priya Gupta",
    role: "SEO Specialist",
    bio: "Optimizes websites for search engines and implements data-driven strategies to improve organic visibility.",
    src: member2,
    alt: "Priya Gupta - SEO Specialist",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Rohit Kumar",
    role: "Frontend Developer",
    bio: "Builds responsive and interactive user interfaces using modern frameworks and cutting-edge technologies.",
    src: member3,
    alt: "Rohit Kumar - Frontend Developer",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Kavya Nair",
    role: "Social Media Manager",
    bio: "Manages brand presence across social platforms and creates engaging campaigns that drive community growth.",
    src: member4,
    alt: "Kavya Nair - Social Media Manager",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Amit Agarwal",
    role: "DevOps Engineer",
    bio: "Streamlines deployment processes and maintains cloud infrastructure for optimal performance and reliability.",
    src: member5,
    alt: "Amit Agarwal - DevOps Engineer",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Neha Bansal",
    role: "Graphic Designer",
    bio: "Creates visually stunning graphics and illustrations that enhance brand identity and user engagement.",
    src: member6,
    alt: "Neha Bansal - Graphic Designer",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Vikram Reddy",
    role: "QA Engineer",
    bio: "Ensures product quality through comprehensive testing and maintains high standards across all deliverables.",
    src: member1,
    alt: "Vikram Reddy - QA Engineer",
    linkedin: "#",
    label: "View on LinkedIn",
  },
  {
    name: "Ananya Iyer",
    role: "Business Analyst",
    bio: "Bridges the gap between business requirements and technical solutions to deliver optimal project outcomes.",
    src: member2,
    alt: "Ananya Iyer - Business Analyst",
    linkedin: "#",
    label: "View on LinkedIn",
  },
];
